spring.application.name=negocio
spring.datasource.url=jdbc:mysql://localhost:3306/nanosland_db?serverTimezone=America/Mexico_City&connectionTimeZone=America/Mexico_City&preserveInstants=false
spring.datasource.username=root
spring.datasource.password=itson
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Esta es la l�nea que le dice a Hibernate que cree/actualice las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=America/Mexico_City
